[package]
name = "gen_test_data"
version = "0.1.0"
edition = "2021"

[dependencies]
dcap-rs = { git = "https://github.com/automata-network/dcap-rs.git", rev = "bd86987" }
preprocess = { path = "../../crates/preprocess" }
