[package]
name = "preprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dcap-rs = { git = "https://github.com/automata-network/dcap-rs.git", rev = "bd86987" }
ethnum = "1.5.0"
hex = "0.4.3"
serde = "1.0.215"
serde_json = "1.0.133"
