[package]
name = "tdx-cairo-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
parser = {path = "../parser"}
dcap-rs.workspace = true
