[package]
name = "parser"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dcap-rs.workspace = true
hex = "0.4.3"
serde = "1.0.215"
cairo-vm.workspace = true
