use super::{QuoteHeader, CertData, body::QuoteBody};

// #[derive(Clone, Debug)]
pub struct QuoteV4 {
    // [48 bytes]
    // Header of Quote data structure.
    // This field is transparent (the user knows its internal structure).
    // Rest of the Quote data structure can be treated as opaque (hidden from the user).
    pub header: QuoteHeader,
    // May either contain a SGX Enclave Report (384 bytes) or TD10 Report (584 bytes)
    pub quote_body: QuoteBody,
    // [4 bytes]
    pub signature_len: u32,
    //  Size of the Quote Signature Data structure in bytes.
    // [variable bytes]
    pub signature: QuoteSignatureDataV4,
}

pub struct QuoteSignatureDataV4 {
    // [64 bytes]
    // ECDSA signature, the r component followed by the s component, 2 x 32 bytes.
    // Public part of the Attestation Key generated by the Quoting Enclave.
    pub quote_signature: [u8; 64],
    // [64 bytes]
    // EC KT-I Public Key, the x-coordinate followed by the y-coordinate (on the RFC 6090 P-256
    // curve), 2 x 32 bytes.
    // Public part of the Attestation Key generated by the Quoting Enclave.
    pub ecdsa_attestation_key: [u8; 64],
    // [variable bytes]
    // QE Cert Data
    pub qe_cert_data: CertData,
}
