[package]
name = "dcap_cairo"
version = "0.1.0"
edition = "2024_07"


[dependencies]
alexandria_data_structures = {git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "95d98a5"}

[dev-dependencies]
cairo_test = "2.8.4"
